### PR TITLE
Added Facebook logo

### PR DESCRIPTION
**Pull request by MarioFPVdev**

### CODE REVIEW

**Comment by FlyRouter** [comment]
Thank you, we will review the application as soon as possible.

I approve it, but from the side of the site administrator @themactep may need some minor edits on the correct image of the logo and something else maybe.

Please expect.

**Comment by themactep** [comment]
Mario, can you please find an svg version of the logo? The website uses responsive layout, and we try to keep graphics crisp on any screen resolution. Raster images are not good for scaling while vector images are. Also, please keep filenames lowercase. Thank you.

**Comment by FlyRouter** [comment]
@MarioFPVdev
I think this option will suit us better for the color and style of the dnv bottom of the site.
We are waiting for your corrections, Mario

https://pixlok.com/icons/facebook-icon-svg-free-download-5/

**Comment by FlyRouter** [comment]
I accidentally sent the new FB logo to the repository.....

**Comment by FlyRouter** [comment]
Closed as another file has been sent.

**Pull request closed without merging**
